name: minimal_time_tracker
description: Minimal Time Tracker

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  localization: ^2.1.0
  intl: ^0.17.0
  hive: ^2.2.3
  hive_generator: ^1.1.3
  hive_flutter: ^1.1.0
  shared_preferences: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:

  uses-material-design: true
  generate: true
