name: Flutter CI

on:
  push:
    branches: [ main ]
    
jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          cache: true
      - run: flutter pub get
      - run: flutter test
      
